name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.4.2
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  http: ^0.13.3
  http_parser: ^4.0.0
  logging: ^1.1.1
  sync: ^0.3.0

dev_dependencies:
  test: ^1.22.2
